-- ===== 与采购请求关连.xlsx =====
SELECT
    "PSHNUM_0" AS "请求号",
    "PSDLIN_0" AS "行",
    "POHNUM_0" AS "订单号",
    "POPLIN_0" AS "订单行",
    "POQSEQ_0" AS "序列号",
    "QTYPUU_0" AS "采购单位数量",
    "PUU_0" AS "PO单位",
    "QTYSTU_0" AS "存货单位数量",
    "STU_0" AS "存货订单单位",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "CREUSR_0" AS "用户",
    "UPDUSR_0" AS "用户"
FROM "与采购请求关连";

-- ===== 供应商价格 (记录).xlsx =====
SELECT
    "PLI_0" AS "价目表代码",
    "PLICRD_0" AS "价格记录",
    "PLICRDIDX_0" AS "索引",
    "PLISTRDAT_0" AS "有效从",
    "PLIENDDAT_0" AS "有效至",
    "LINNBR_0" AS "行数",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "改变创建者",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "VALSTA_0" AS "审核状态"
FROM "供应商价格 (记录)";

-- ===== 供应商价格.xlsx =====
SELECT
    "PLI_0" AS "价目表代码",
    "PLICRD_0" AS "价格记录",
    "PLILIN_0" AS "行",
    "PLICRI_0" AS "标准",
    "PLICRI1_0" AS "标准1",
    "PLICRI2_0" AS "标准2",
    "PLICRI3_0" AS "标准3",
    "PLICRI4_0" AS "标准4",
    "PLICRI5_0" AS "标准5",
    "PLISTRDAT_0" AS "有效从",
    "PLIENDDAT_0" AS "有效至",
    "CPNITMREF_0" AS "组件产品",
    "UOM_0" AS "单位",
    "CUR_0" AS "货币",
    "MINQTY_0" AS "最小数量",
    "MAXQTY_0" AS "最大数量",
    "MINAMT_0" AS "最小值",
    "MAXAMT_0" AS "最大值",
    "PRIDIV_0" AS "价格系数",
    "PRI_0" AS "单价",
    "DCGVAL_0" AS "收费 / 折扣值",
    "LTI_0" AS "提前期",
    "FOCQTYMIN_0" AS "最小免费开始时间",
    "FOCQTYBKT_0" AS "免费分配级别",
    "FOCAMTMIN_0" AS "最小免费开始时间",
    "FOCAMTBKT_0" AS "免费分配级别",
    "FOCITMREF_0" AS "免费产品",
    "FOCUOM_0" AS "单位",
    "FOCQTY_0" AS "免费数量",
    "COMCOE_0" AS "佣金因素",
    "IMPNUMLIG_0" AS "导入行",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符"
FROM "供应商价格";

-- ===== 到货单.xlsx =====
SELECT
    "YPTHNUM_0" AS "收货号",
    "CPY_0" AS "公司",
    "PRHFCY_0" AS "收货地点",
    "RCPDAT_0" AS "收货日期",
    "BPSNUM_0" AS "供应商",
    "BPAADD_0" AS "地址",
    "CUR_0" AS "货币",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "SOHNUM_0" AS "订单号",
    "APPFLG_0" AS "已签字",
    "YPTHFLG_0" AS "单据状态",
    "QUSR_0" AS "检验员",
    "QDAT_0" AS "检验日期",
    "YNOTE_0" AS "备注",
    "XSRMID_0" AS "SRMID"
FROM "到货单";

-- ===== 到货单明细.xlsx =====
SELECT
    "YPTHNUM_0" AS "收货号",
    "YPTDLIN_0" AS "行",
    "CPY_0" AS "公司",
    "PRHFCY_0" AS "收货地点",
    "RCPDAT_0" AS "收货日期",
    "POHFCY_0" AS "采购地点",
    "POHNUM_0" AS "订单号",
    "POPLIN_0" AS "订单行",
    "POQSEQ_0" AS "订单序列数",
    "POHTYP_0" AS "订单类型",
    "BPSNUM_0" AS "供应商",
    "ITMREF_0" AS "产品",
    "GROPRI_0" AS "毛价",
    "CPRCUR_0" AS "公司货币",
    "UOM_0" AS "单位",
    "QTYUOM_0" AS "已收到",
    "RRRQTYPUU_0" AS "配置R采购数量",
    "RTNQTYPUU_0" AS "退货采购",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "改变用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "LINAPPFLG_0" AS "签约货品",
    "LOT_0" AS "批次",
    "XSAMQTY_0" AS "抽样数量",
    "QUAFLG_0" AS "质量控制管理",
    "TECCRD_0" AS "技术列表",
    "STOTST_0" AS "接收建议",
    "RTNDAT_0" AS "退货日期",
    "DES_0" AS "描述",
    "AQTYUOM_0" AS "合格数量",
    "PTHFLG_0" AS "收货标志",
    "PTHNUM_0" AS "收货号",
    "PTDLIN_0" AS "行",
    "ZITMDES4_0" AS "规格型号",
    "YPTDFLG_0" AS "状态",
    "YRETFLG_0" AS "是否退货",
    "ZJAUS_0" AS "质检人",
    "ZJDAT_0" AS "质检日期",
    "YQTYUOM_0" AS "收货数量",
    "XSRMLIN_0" AS "SRM Line"
FROM "到货单明细";

-- ===== 收货.xlsx =====
SELECT
    "PTHNUM_0" AS "收货号",
    "CPY_0" AS "公司",
    "PRHFCY_0" AS "收货地点",
    "PURTYP_0" AS "采购类型",
    "BPSNDE_0" AS "供应商运输附注号",
    "NDEDAT_0" AS "包装单日期",
    "RCPDAT_0" AS "收货日期",
    "BPSNUM_0" AS "供应商",
    "BPAADD_0" AS "地址",
    "BPOADD_0" AS "装运地址",
    "BPONAM_0" AS "公司名称",
    "BPOADDLIG_0" AS "地址行",
    "BPOPOSCOD_0" AS "邮政编码",
    "BPOCTY_0" AS "城市",
    "BPOSAT_0" AS "省/直辖市/自治区",
    "BPOCRY_0" AS "国家",
    "BPOCRYNAM_0" AS "国家名称",
    "BPSINV_0" AS "供应商发票",
    "BPAINV_0" AS "开票地址",
    "BPRPAY_0" AS "付至",
    "BPAPAY_0" AS "支付BP地址",
    "BPTNUM_0" AS "承运人号",
    "FFWNUM_0" AS "货运承揽商号",
    "FFWADD_0" AS "运输商地址",
    "TSSCOD_0" AS "统计组",
    "CUR_0" AS "货币",
    "CHGTYP_0" AS "汇率类型",
    "CHGCOE_0" AS "汇率",
    "VACBPR_0" AS "税则",
    "VACTYP_0" AS "税则类型",
    "DEP_0" AS "折扣代码",
    "MDL_0" AS "发货模式",
    "EECNAT_0" AS "EEC 交易属性",
    "EECSCH_0" AS "EEC 规则",
    "EECTRN_0" AS "EEC 传送模式",
    "EECICT_0" AS "国际贸易术语",
    "ICTCTY_0" AS "国际贸易术语城镇",
    "EECLOC_0" AS "EEC 运输地址",
    "EECNUM_0" AS "EEC 标识",
    "EECNUMDEB_0" AS "借方",
    "GPGCOD_0" AS "分组",
    "WEU_0" AS "重量单位",
    "VOU_0" AS "体积单位",
    "TOTGROWEI_0" AS "毛重",
    "TOTNETWEI_0" AS "净重",
    "TOTVOL_0" AS "体积",
    "LINNBR_0" AS "行数",
    "INVLINNBR_0" AS "开完发票的行数",
    "INVLINCTR_0" AS "开票货品数",
    "PSTLINNBR_0" AS "已过账行数",
    "PRNFLG_0" AS "已打印",
    "INVFLG_0" AS "已开票",
    "PSTFLG_0" AS "已过账",
    "PSTDAT_0" AS "反转日期",
    "BETFCY_0" AS "地点间",
    "BETCPY_0" AS "公司间",
    "TEX1_0" AS "文本号",
    "TEX2_0" AS "文本",
    "TRSCOD_0" AS "交易代码",
    "ENTCOD_0" AS "自动日记账",
    "CAI_0" AS "CAI号",
    "DATVLYCAI_0" AS "CAI有效日期",
    "TYPVCR_0" AS "文档类型",
    "CLSVCR_0" AS "分类",
    "SCUVCR_0" AS "分支",
    "SEQVCR_0" AS "序列",
    "DIE_0" AS "分析元类型代码",
    "CCE_0" AS "分析元",
    "DSPWEU_0" AS "重量单位",
    "DSPVOU_0" AS "体积单位",
    "TOTLINAMT_0" AS "不含税行总计",
    "TOTLINQTY_0" AS "总货品数量",
    "TOTLINWEU_0" AS "行称重合计",
    "TOTLINVOU_0" AS "行体积合计",
    "TOTAMTNOT_0" AS "不含税总计",
    "TOTAMTNOTL_0" AS "不含税金额-公司币种",
    "TOTTAXAMT_0" AS "税费总计",
    "TOTAMTATI_0" AS "含税总计",
    "TOTAMTATIL_0" AS "含税金额-公司币种",
    "INVDTALIN1_0" AS "发票行元素",
    "INVDTAVAT1_0" AS "价格明细税",
    "INVDTALIN2_0" AS "发票货品 Alloc 元素",
    "INVDTAVAT2_0" AS "分配行税",
    "WRHE_0" AS "仓库",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "LICPLATE_0" AS "注册",
    "TRLLICPLATE_0" AS "拖车牌照",
    "DPEDAT_0" AS "离开日期",
    "ARVDAT_0" AS "抵达日期",
    "ETD_0" AS "发出时间",
    "ETA_0" AS "到达时间",
    "ZNOTE_0" AS "备注",
    "ZAUTOFLG_0" AS "自动发货T7",
    "ZAUTOLOG_0" AS "自动发货日志"
FROM "收货";

-- ===== 收货明细.xlsx =====
SELECT
    "PTHNUM_0" AS "收货号",
    "PTDLIN_0" AS "行",
    "CPY_0" AS "公司",
    "PRHFCY_0" AS "收货地点",
    "RCPDAT_0" AS "收货日期",
    "POHFCY_0" AS "采购地点",
    "POHNUM_0" AS "订单号",
    "POPLIN_0" AS "订单行",
    "POQSEQ_0" AS "订单序列数",
    "POHTYP_0" AS "订单类型",
    "BPSNUM_0" AS "供应商",
    "BPSINV_0" AS "供应商发票",
    "BPAINV_0" AS "开票地址",
    "PJT_0" AS "项目",
    "ITMREF_0" AS "产品",
    "ITMDES1_0" AS "产品描述",
    "ITMDES_0" AS "翻译后的产品描述",
    "GROPRI_0" AS "毛价",
    "PRIREN_0" AS "定价理由",
    "DISCRGVAL1_0" AS "折扣/收费 值1",
    "DISCRGVAL2_0" AS "折扣/收费 值2",
    "DISCRGVAL3_0" AS "折扣/收费 值3",
    "DISCRGVAL4_0" AS "折扣/收费 值4",
    "DISCRGVAL5_0" AS "折扣/收费 值5",
    "DISCRGVAL6_0" AS "折扣/收费 值6",
    "DISCRGVAL7_0" AS "折扣/收费 值7",
    "DISCRGVAL8_0" AS "折扣/收费 值8",
    "DISCRGVAL9_0" AS "折扣/收费 值9",
    "DISCRGREN1_0" AS "折扣 1理由",
    "DISCRGREN2_0" AS "折扣 2理由",
    "DISCRGREN3_0" AS "折扣 3理由",
    "DISCRGREN4_0" AS "折扣 4理由",
    "DISCRGREN5_0" AS "折扣 5理由",
    "DISCRGREN6_0" AS "折扣 6理由",
    "DISCRGREN7_0" AS "折扣 7理由",
    "DISCRGREN8_0" AS "折扣 8理由",
    "DISCRGREN9_0" AS "折扣 9理由",
    "NETPRI_0" AS "净价",
    "NETPRIPUU_0" AS "采购净价",
    "LINAMT_0" AS "不含税行金额",
    "LINAMTCPR_0" AS "存货成本",
    "LINCSTPUR_0" AS "采购成本",
    "LINATIAMT_0" AS "含税行金额",
    "DISCRGAMT1_0" AS "付款 /收费 1",
    "DISCRGAMT2_0" AS "付款 /收费 2",
    "DISCRGAMT3_0" AS "付款 /收费 3",
    "DISCRGAMT4_0" AS "折扣/费用4",
    "DISCRGAMT5_0" AS "折扣/费用5",
    "DISCRGAMT6_0" AS "折扣/费用6",
    "DISCRGAMT7_0" AS "折扣/费用7",
    "DISCRGAMT8_0" AS "折扣/费用8",
    "DISCRGAMT9_0" AS "折扣/费用9",
    "CLCAMT1_0" AS "1号计算税基",
    "CLCAMT2_0" AS "2号计算税基",
    "CLCAMT3_0" AS "税费计算3基数",
    "CLCAMT4_0" AS "税费计算4基数",
    "CLCAMT5_0" AS "税费计算5基数",
    "CLCAMT6_0" AS "税费计算6基数",
    "CLCAMT7_0" AS "税费计算7基数",
    "DISBASLIN1_0" AS "税基折扣 1",
    "BASTAXLIN1_0" AS "税基 1",
    "AMTTAXLIN1_0" AS "税额 1",
    "AMTTAXLIN2_0" AS "税额 2",
    "AMTTAXLIN3_0" AS "税号3",
    "AMTTAXRCP_0" AS "接收税金额",
    "AMTTAXISS_0" AS "付款税金额",
    "AMTTAXOTH1_0" AS "金额其他税1",
    "AMTTAXOTH2_0" AS "金额其他税2",
    "DEDTAXLIN1_0" AS "可减免税1",
    "DEDTAXLIN2_0" AS "可减免税2",
    "DEDTAXLIN3_0" AS "可减免税3",
    "DEDTAXRCP_0" AS "可扣除税",
    "DEDTAXISS_0" AS "可扣除税",
    "DEDTAXOTH1_0" AS "可扣除税",
    "DEDTAXOTH2_0" AS "可扣除税",
    "CPRPRI_0" AS "没有收入费用的实际价格",
    "CPR_0" AS "成本价",
    "CPRCLC_0" AS "已计算的单位存货成本",
    "CSTPUR_0" AS "单位采购成本",
    "CPRCOE_0" AS "收货成本因素",
    "CPRAMT_0" AS "单位固定成本",
    "STCNUM_0" AS "成本结构",
    "NETCUR_0" AS "货币",
    "CPRCUR_0" AS "公司货币",
    "FCSCSTPUR_0" AS "采购成本总计",
    "FCSCPR_0" AS "存货成本总计",
    "FCSCPRCPT_0" AS "已入账的存货成本总计",
    "QTYUOM_0" AS "已收到",
    "QTYPUU_0" AS "采购单位数量",
    "QTYSTU_0" AS "存货单位数量",
    "QTYWEU_0" AS "重量",
    "LINWEU_0" AS "重量单位",
    "QTYVOU_0" AS "体积",
    "LINVOU_0" AS "体积",
    "UOM_0" AS "收货单位",
    "PUU_0" AS "采购单位",
    "STU_0" AS "存货单位",
    "UOMPUUCOE_0" AS "STK- PUR 转换",
    "UOMSTUCOE_0" AS "STK 转换",
    "RRRQTYPUU_0" AS "配置R采购数量",
    "RRRQTYSTU_0" AS "配置R存货数量",
    "RTNQTYPUU_0" AS "退货采购",
    "RTNQTYSTU_0" AS "退货库存数量",
    "INVQTYPUU_0" AS "开票采购",
    "INVQTYSTU_0" AS "开票库存",
    "LINPRNFLG_0" AS "已打印的行",
    "LININVFLG_0" AS "开票行",
    "LINEECFLG_0" AS "借方行",
    "LINPSTFLG_0" AS "已入账货品",
    "LINPSTDAT_0" AS "反转日期",
    "QUAFLG_0" AS "质量控制管理",
    "QUARTNFLG_0" AS "来自 QC 退货",
    "LINPURTYP_0" AS "采购类型",
    "EECINCRAT_0" AS "EEC 统计增加",
    "ORICRY_0" AS "原产地",
    "BPOCRY_0" AS "装运地区",
    "SATISS_0" AS "发送区域",
    "TSICOD_0" AS "统计组",
    "TRSFAM_0" AS "交易组",
    "VAT_0" AS "税费",
    "TAXRCP_0" AS "进项税",
    "TAXISS_0" AS "销项税",
    "TAXOTH1_0" AS "其他税费1",
    "TAXOTH2_0" AS "其他税费2",
    "LINTEX_0" AS "文本号",
    "SDHNUM_0" AS "发货号",
    "SDDLIN_0" AS "装运行",
    "LINSTOFCY_0" AS "装运地点",
    "ITMREFORI_0" AS "已发放产品",
    "VCRTYPORI_0" AS "原始凭证类型",
    "VCRNUMORI_0" AS "源凭证号",
    "VCRLINORI_0" AS "源凭证货品号",
    "VCRSEQORI_0" AS "原始凭证序列号",
    "STOMGTCOD_0" AS "存货管理",
    "VERFLG_0" AS "版本标识",
    "LINTYP_0" AS "行类型",
    "LINCAT_0" AS "移动类型",
    "LIKQTYCOE_0" AS "相关质量参数",
    "WRH_0" AS "仓库",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "MATTOL_0" AS "三向匹配",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "SCOCSTCPT_0" AS "已过账的外协成本",
    "YPTHNUM_0" AS "收货号",
    "YPTDLIN_0" AS "行",
    "YPIFLG_0" AS "不暂估",
    "XWSPK_0" AS "TotalLINK PK"
FROM "收货明细";

-- ===== 采购数量.xlsx =====
SELECT
    "POHNUM_0" AS "订单号",
    "POPLIN_0" AS "订单行",
    "POQSEQ_0" AS "序列号",
    "POQLNK_0" AS "行＋序列 （供连接）",
    "CPY_0" AS "公司",
    "POHFCY_0" AS "采购地点",
    "POHTYP_0" AS "订单类型",
    "ORDDAT_0" AS "订单日期",
    "BPSNUM_0" AS "供应商",
    "BPSINV_0" AS "开票至",
    "BPAINV_0" AS "开票地址",
    "LINREVNUM_0" AS "版本号",
    "ITMREF_0" AS "产品",
    "ITMREFBPS_0" AS "供应商产品",
    "PUU_0" AS "采购单位",
    "STU_0" AS "存货单位",
    "UOM_0" AS "订单单位",
    "UOMFLG_0" AS "订单PAC",
    "UOMPUUCOE_0" AS "STK- PUR 转换",
    "LIKQTYCOE_0" AS "相关质量参数",
    "QTYUOM_0" AS "已订购",
    "QTYPUU_0" AS "采购单位数量",
    "QTYSTU_0" AS "存货单位数量",
    "QTYWEU_0" AS "重量",
    "LINWEU_0" AS "重量单位",
    "QTYVOU_0" AS "体积",
    "LINVOU_0" AS "体积",
    "RETQTYPUU_0" AS "需要的采购数量",
    "RETQTYSTU_0" AS "需要的库存数量",
    "RCPQTYPUU_0" AS "已收采购货品",
    "RCPQTYSTU_0" AS "已收库存",
    "INVQTYPUU_0" AS "开票采购",
    "INVQTYSTU_0" AS "开票库存",
    "RETRCPDAT_0" AS "需求日期",
    "EXTRCPDAT_0" AS "预期收货日期",
    "LINSTOFCY_0" AS "装运地点",
    "PRHFCY_0" AS "收货地点",
    "FCYADD_0" AS "收货地址",
    "OFS_0" AS "补货提前期",
    "USEPLC_0" AS "库位参考",
    "SCOADD_0" AS "外协地址",
    "WIPTYP_0" AS "订单类型",
    "WIPSTA_0" AS "在产品状态",
    "WIPNUM_0" AS "订单号",
    "LINPURTYP_0" AS "采购类型",
    "LASRCPDAT_0" AS "上次收货日期",
    "LASINVDAT_0" AS "最新发票日期",
    "INVRCPNBR_0" AS "开票收货数",
    "LINRCPNBR_0" AS "收货数",
    "LININVNBR_0" AS "发票数",
    "LINTEX_0" AS "文本号",
    "RCPCLEFLG_0" AS "收到完成",
    "LINCLEFLG_0" AS "已关闭的行",
    "LININVFLG_0" AS "开票行",
    "LINPRNFLG_0" AS "已打印的行",
    "CMMTAX_0" AS "承诺类型",
    "CMMNUM_0" AS "承诺编号",
    "CMMFLG_0" AS "承诺标示器",
    "FBUFLG_0" AS "预算超支",
    "ORI_0" AS "请求来源",
    "LINOCNDAT_0" AS "确认函日期",
    "LINOCNNUM_0" AS "订单确认函编号",
    "LINOCNFLG_0" AS "订单确认函指示符",
    "NETCUR_0" AS "货币",
    "CPRCOE_0" AS "收货成本因素",
    "CPRAMT_0" AS "单位固定成本",
    "STCNUM_0" AS "成本结构",
    "CSTPUR_0" AS "单位采购成本",
    "CPR_0" AS "单位存货成本",
    "CPRCUR_0" AS "公司货币",
    "CPRPRI_0" AS "没有收入费用的实际价格",
    "FCSCSTPUR_0" AS "采购成本总计",
    "FCSCPR_0" AS "存货成本总计",
    "LINAMT_0" AS "不含税行金额",
    "LINAMTCPR_0" AS "存货成本",
    "LINCSTPUR_0" AS "采购成本",
    "REACSTPUR_0" AS "实际采购成本",
    "LINATI_0" AS "含税行金额",
    "LINATIAMT_0" AS "含税行金额",
    "DISCRGAMT1_0" AS "付款 /收费 1",
    "DISCRGAMT2_0" AS "付款 /收费 2",
    "DISCRGAMT3_0" AS "付款 /收费 3",
    "DISCRGAMT4_0" AS "折扣/费用4",
    "DISCRGAMT5_0" AS "折扣/费用5",
    "DISCRGAMT6_0" AS "折扣/费用6",
    "DISCRGAMT7_0" AS "折扣/费用7",
    "DISCRGAMT8_0" AS "折扣/费用8",
    "DISCRGAMT9_0" AS "折扣/费用9",
    "CLCAMT1_0" AS "1号计算税基",
    "CLCAMT2_0" AS "2号计算税基",
    "CLCAMT3_0" AS "税费计算3基数",
    "CLCAMT4_0" AS "税费计算4基数",
    "CLCAMT5_0" AS "税费计算5基数",
    "CLCAMT6_0" AS "税费计算6基数",
    "CLCAMT7_0" AS "税费计算7基数",
    "DISBASLIN1_0" AS "税基折扣 1",
    "BASTAXLIN1_0" AS "税基 1",
    "AMTTAXLIN1_0" AS "税额 1",
    "AMTTAXLIN2_0" AS "税额 2",
    "AMTTAXLIN3_0" AS "税号3",
    "AMTTAXRCP_0" AS "接收税金额",
    "AMTTAXISS_0" AS "付款税金额",
    "AMTTAXOTH1_0" AS "金额其他税1",
    "AMTTAXOTH2_0" AS "金额其他税2",
    "DEDTAXLIN1_0" AS "可减免税1",
    "DEDTAXLIN2_0" AS "可减免税2",
    "DEDTAXLIN3_0" AS "可减免税3",
    "DEDTAXRCP_0" AS "可扣除税",
    "DEDTAXISS_0" AS "可扣除税",
    "DEDTAXOTH1_0" AS "可扣除税",
    "DEDTAXOTH2_0" AS "可扣除税",
    "PQHNUM_0" AS "询价单号",
    "PPDLIN_0" AS "反馈行",
    "SOHNUM_0" AS "销售订单号",
    "SOPLIN_0" AS "订单行",
    "SOQSEQ_0" AS "序列号",
    "SDHNUM_0" AS "发货号",
    "SDDLIN_0" AS "装运行",
    "CAD_0" AS "频率",
    "YEA_0" AS "年份",
    "MON_0" AS "月份",
    "WEE_0" AS "星期号",
    "LINSTA_0" AS "行状态",
    "LINTYP_0" AS "行类型",
    "DEMRCPDAT_0" AS "请求交货日期",
    "DEMRCPHOU_0" AS "请求交货时间",
    "DEMENDDAT_0" AS "请求结束日期",
    "DEMENDHOU_0" AS "请求结束时间",
    "ITMREFORI_0" AS "已发放产品",
    "VCRTYPORI_0" AS "原始凭证类型",
    "VCRNUMORI_0" AS "源凭证号",
    "VCRLINORI_0" AS "源凭证货品号",
    "VCRSEQORI_0" AS "原始凭证序列号",
    "PTHNUM_0" AS "收货号",
    "PTDLIN_0" AS "行",
    "OCNLIN_0" AS "公司间销售行",
    "OCNSEQ_0" AS "公司间销售序号",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "ZQTYUOM_0" AS "到货数量",
    "YMILLS_0" AS "钢厂",
    "XWSPK_0" AS "TotalLINK PK",
    "XSRMLIN_0" AS "SRM Line"
FROM "采购数量";

-- ===== 采购订单.xlsx =====
SELECT
    "POHNUM_0" AS "订单号",
    "CPY_0" AS "公司",
    "POHFCY_0" AS "采购地点",
    "POHTYP_0" AS "订单类型",
    "PURTYP_0" AS "采购类型",
    "REVNUM_0" AS "版本号",
    "ORDDAT_0" AS "订单日期",
    "ORDREF_0" AS "内部或订单参考",
    "BPSNUM_0" AS "供应商",
    "BPAADD_0" AS "地址",
    "BPRNAM_0" AS "公司名称",
    "BPAADDLIG_0" AS "地址行",
    "POSCOD_0" AS "邮政编码",
    "CTY_0" AS "城市",
    "SAT_0" AS "省/直辖市/自治区",
    "CRY_0" AS "国家",
    "CRYNAM_0" AS "国家名称",
    "BPOADD_0" AS "装运地址",
    "BPONAM_0" AS "公司名称",
    "BPOADDLIG_0" AS "地址行",
    "BPOPOSCOD_0" AS "邮政编码",
    "BPOCTY_0" AS "城市",
    "BPOSAT_0" AS "省/直辖市/自治区",
    "BPOCRY_0" AS "国家",
    "BPOCRYNAM_0" AS "国家名称",
    "INVFCY_0" AS "开票地点",
    "RCPFCY_0" AS "收货地点",
    "EXTRCPDAT1_0" AS "预期收货日期",
    "TSSCOD_0" AS "统计组",
    "PTE_0" AS "付款条件",
    "DEP_0" AS "折扣代码",
    "MDL_0" AS "发货模式",
    "BPTNUM_0" AS "承运人",
    "BPRPAY_0" AS "付至",
    "BPAPAY_0" AS "支付BP地址",
    "BPSINV_0" AS "开票至",
    "BPAINV_0" AS "开票地址",
    "EECICT_0" AS "国际贸易术语",
    "ICTCTY_0" AS "国际贸易术语城镇",
    "GPGCOD_0" AS "分组",
    "FFWNUM_0" AS "货运承揽商号",
    "FFWADD_0" AS "运输商地址",
    "EECLOC_0" AS "EEC 运输地址",
    "EECNUM_0" AS "EEC 标识",
    "BUY_0" AS "采购员",
    "DIE_0" AS "分析元类型代码",
    "CCE_0" AS "分析元",
    "LAN_0" AS "语言",
    "CUR_0" AS "货币",
    "CHGTYP_0" AS "汇率类型",
    "CHGCOE_0" AS "汇率",
    "VACBPR_0" AS "税则",
    "VACTYP_0" AS "税则类型",
    "DISCRGTYP_0" AS "折扣 /收费价值类型",
    "LINNBR_0" AS "行数",
    "FBULINNBR_0" AS "预算外货品数",
    "RCPLINNBR_0" AS "收到货品数",
    "CLELINNBR_0" AS "完成货品数",
    "INVLINNBR_0" AS "开票货品数",
    "RCPNBR_0" AS "收货数",
    "INVNBR_0" AS "发票数",
    "APPFLG_0" AS "已签字",
    "CLEFLG_0" AS "已结转",
    "RCPFLG_0" AS "已收货",
    "INVFLG_0" AS "已开票",
    "PRNFLG_0" AS "已打印",
    "COPNBR_0" AS "订单副本号",
    "TEX1_0" AS "文本号",
    "TEX2_0" AS "文本",
    "OCNDAT_0" AS "许可日期",
    "OCNNUM_0" AS "订单确认函编号",
    "OCNREM_0" AS "订单确认函备注",
    "OCNFLG_0" AS "确认函提醒",
    "FUPFLG_0" AS "迟运提醒",
    "BETCPY_0" AS "公司间",
    "BETFCY_0" AS "地点间",
    "ORIFCY_0" AS "来源 / 寄件人地点",
    "STOFCY_0" AS "装运地点",
    "SALFCY_0" AS "销售地点",
    "SOHCAT_0" AS "订单类型",
    "BPCORD_0" AS "订单客户",
    "DME_0" AS "部分发货",
    "DSPWEU_0" AS "重量单位",
    "DSPVOU_0" AS "体积单位",
    "TOTLINATI_0" AS "含税行总计",
    "TOTLINAMT_0" AS "不含税行总计",
    "TOTLINQTY_0" AS "总货品数量",
    "TOTLINWEU_0" AS "行称重合计",
    "TOTLINVOU_0" AS "行体积合计",
    "TOTTAXAMT_0" AS "税费总计",
    "INVDTALIN1_0" AS "发票行元素",
    "INVDTAVAT1_0" AS "价格明细税",
    "INVDTALIN2_0" AS "发票货品 Alloc 元素",
    "INVDTAVAT2_0" AS "分配行税",
    "TOTORD_0" AS "订单总计不含税",
    "TTVORD_0" AS "订单总计 +税",
    "TOTORDL_0" AS "不含税订单总额/币种",
    "TTVORDL_0" AS "含税订单总额/币种",
    "TOTVLT_0" AS "预期总额－税款",
    "STRDAT_0" AS "有效从",
    "ENDDAT_0" AS "有效至",
    "SINUM_0" AS "整体部分编号",
    "EXPNUM_0" AS "导出编号",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符",
    "VALSTA_0" AS "审核状态",
    "XSFX_0" AS "Suffix",
    "XLOCDET_0" AS "库位",
    "XSRMID_0" AS "SRMID"
FROM "采购订单";

-- ===== 采购需求明细.xlsx =====
SELECT
    "PSHNUM_0" AS "请求号",
    "PSDLIN_0" AS "行",
    "CPY_0" AS "公司",
    "PSHFCY_0" AS "请求地点",
    "ITMREF_0" AS "产品",
    "ITMDES1_0" AS "产品描述",
    "ITMDES_0" AS "翻译后的产品描述",
    "BPSNUM_0" AS "供应商",
    "QTYPUU_0" AS "采购单位数量",
    "QTYSTU_0" AS "存货单位数量",
    "ORDQTYPUU_0" AS "已订货采购",
    "ORDQTYSTU_0" AS "已订货库存",
    "PUU_0" AS "采购单位",
    "STU_0" AS "存货单位",
    "VACBPR_0" AS "税则",
    "VACTYP_0" AS "税则类型",
    "CUR_0" AS "货币",
    "CHGTYP_0" AS "汇率类型",
    "CHGCOE_0" AS "汇率",
    "GROPRI_0" AS "毛价",
    "NETPRI_0" AS "净价",
    "DISCRGVAL1_0" AS "折扣/收费 值1",
    "DISCRGVAL2_0" AS "折扣/收费 值2",
    "DISCRGVAL3_0" AS "折扣/收费 值3",
    "DISCRGVAL4_0" AS "折扣/收费 值4",
    "DISCRGVAL5_0" AS "折扣/收费 值5",
    "DISCRGVAL6_0" AS "折扣/收费 值6",
    "DISCRGVAL7_0" AS "折扣/收费 值7",
    "DISCRGVAL8_0" AS "折扣/收费 值8",
    "DISCRGVAL9_0" AS "折扣/收费 值9",
    "PRIREN_0" AS "定价理由",
    "DISCRGREN1_0" AS "折扣 1理由",
    "DISCRGREN2_0" AS "折扣 2理由",
    "DISCRGREN3_0" AS "折扣 3理由",
    "DISCRGREN4_0" AS "折扣 4理由",
    "DISCRGREN5_0" AS "折扣 5理由",
    "DISCRGREN6_0" AS "折扣 6理由",
    "DISCRGREN7_0" AS "折扣 7理由",
    "DISCRGREN8_0" AS "折扣 8理由",
    "DISCRGREN9_0" AS "折扣 9理由",
    "LINAMT_0" AS "不含税行金额",
    "EXTORDDAT_0" AS "计算订单日期",
    "EXTRCPDAT_0" AS "期望交货日期",
    "LINBUY_0" AS "采购员",
    "LINPURTYP_0" AS "采购类型",
    "PJT_0" AS "项目",
    "PRHFCY_0" AS "收货地点",
    "VAT_0" AS "税费",
    "TAXRCP_0" AS "进项税",
    "TAXISS_0" AS "销项税",
    "TAXOTH1_0" AS "其他税费1",
    "TAXOTH2_0" AS "其他税费2",
    "CLCAMT1_0" AS "1号计算税基",
    "CLCAMT2_0" AS "2号计算税基",
    "CLCAMT3_0" AS "税费计算3基数",
    "CLCAMT4_0" AS "税费计算4基数",
    "CLCAMT5_0" AS "税费计算5基数",
    "CLCAMT6_0" AS "税费计算6基数",
    "CLCAMT7_0" AS "税费计算7基数",
    "LINATIAMT_0" AS "含税行金额",
    "BASTAXLIN1_0" AS "税基 1",
    "AMTTAXLIN1_0" AS "税额 1",
    "AMTTAXLIN2_0" AS "税额 2",
    "AMTTAXLIN3_0" AS "税号3",
    "AMTTAXRCP_0" AS "接收税金额",
    "AMTTAXISS_0" AS "付款税金额",
    "AMTTAXOTH1_0" AS "金额其他税1",
    "AMTTAXOTH2_0" AS "金额其他税2",
    "DEDTAXLIN1_0" AS "可减免税1",
    "DEDTAXLIN2_0" AS "可减免税2",
    "DEDTAXLIN3_0" AS "可减免税3",
    "DEDTAXRCP_0" AS "可扣除税",
    "DEDTAXISS_0" AS "可扣除税",
    "DEDTAXOTH1_0" AS "可扣除税",
    "DEDTAXOTH2_0" AS "可扣除税",
    "LINTEX_0" AS "文本号",
    "LINCLEFLG_0" AS "已关闭的行",
    "LINORDFLG_0" AS "订单货品",
    "LINAPPFLG_0" AS "签约货品",
    "CMMPRPTAX_0" AS "承诺类型",
    "CMMPRPNUM_0" AS "预承诺编号",
    "CMMPRPFLG_0" AS "预承诺指示",
    "FBUFLG_0" AS "预算超支",
    "ORI_0" AS "请求来源",
    "PQHNUM_0" AS "询价单号",
    "PPDLIN_0" AS "反馈行",
    "WIPNUM_0" AS "序列数 (计划)",
    "NBAOF_0" AS "No. of Req. for qte",
    "PSDNUMMMS_0" AS "维护行识别码",
    "CREUSR_0" AS "创建用户",
    "CREDAT_0" AS "创建日期",
    "UPDUSR_0" AS "修改用户",
    "UPDDAT_0" AS "修改日期",
    "CREDATTIM_0" AS "日期时间",
    "UPDDATTIM_0" AS "日期时间",
    "AUUID_0" AS "唯一标识符"
FROM "采购需求明细";
