-- ============================================================
-- 01_ods.sql - ODS 层：27 张本体映射表全字段贴源复制
-- 命名：ODS_<原表名>，保留 X3 原列名，追加 ETL_LOAD_TS
-- 执行身份：THBI（DBA 角色，可读 ZJTH）
-- 幂等性：run_build.py 执行前自动 drop-if-exists
-- ============================================================

-- ---------- 主数据（8） ----------
CREATE TABLE THBI.ODS_BPSUPPLIER AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.BPSUPPLIER t;

CREATE TABLE THBI.ODS_BPARTNER AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.BPARTNER t;

CREATE TABLE THBI.ODS_BPCUSTOMER AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.BPCUSTOMER t;

CREATE TABLE THBI.ODS_BPCARRIER AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.BPCARRIER t;

CREATE TABLE THBI.ODS_ITMMASTER AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.ITMMASTER t;

CREATE TABLE THBI.ODS_FACILITY AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.FACILITY t;

CREATE TABLE THBI.ODS_ITMFACILIT AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.ITMFACILIT t;

-- ---------- 采购单据（16） ----------
CREATE TABLE THBI.ODS_PORDER AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PORDER t;

CREATE TABLE THBI.ODS_PORDERQ AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PORDERQ t;

CREATE TABLE THBI.ODS_PREQUISD AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PREQUISD t;

CREATE TABLE THBI.ODS_PREQUISO AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PREQUISO t;

CREATE TABLE THBI.ODS_PQUOTAT AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PQUOTAT t;

CREATE TABLE THBI.ODS_PQUOTATD AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PQUOTATD t;

CREATE TABLE THBI.ODS_YPRECEIPT AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.YPRECEIPT t;

CREATE TABLE THBI.ODS_YPRECEIPTD AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.YPRECEIPTD t;

CREATE TABLE THBI.ODS_PRECEIPT AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PRECEIPT t;

CREATE TABLE THBI.ODS_PRECEIPTD AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PRECEIPTD t;

CREATE TABLE THBI.ODS_PINVOICE AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PINVOICE t;

CREATE TABLE THBI.ODS_PINVOICED AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PINVOICED t;

CREATE TABLE THBI.ODS_PAYMENTH AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PAYMENTH t;

CREATE TABLE THBI.ODS_PAYMENTD AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PAYMENTD t;

-- ---------- 价格（3） ----------
CREATE TABLE THBI.ODS_PPRICCONF AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PPRICCONF t;

CREATE TABLE THBI.ODS_PPRICFICH AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PPRICFICH t;

CREATE TABLE THBI.ODS_PPRICLIST AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.PPRICLIST t;

-- ---------- 制造（3） ----------
CREATE TABLE THBI.ODS_BOM AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.BOM t;

CREATE TABLE THBI.ODS_BOMD AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.BOMD t;

CREATE TABLE THBI.ODS_ROUOPE AS
SELECT t.*, SYSTIMESTAMP AS ETL_LOAD_TS FROM ZJTH.ROUOPE t;
